# Generated by Django 6.0.7 on 2026-07-11 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('India', 'India'), ('Japan', 'Japan'), ('Thailand', 'Thailand'), ('Switzerland', 'Switzerland'), ('Maldives', 'Maldives'), ('France', 'France'), ('Italy', 'Italy'), ('Norway', 'Norway'), ('Dubai', 'Dubai'), ('Bali', 'Bali'), ('Hawaii', 'Hawaii'), ('Egypt', 'Egypt')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('budget', models.CharField(choices=[('Economy', 'Economy'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
